from django.conf import settings
from .constants import AUTHX_CONSTANT_CONFIGS

AUTHX_SETTINGS =  {
    'AUTHX_LOGIN_NAME' : getattr(settings,'AUTHX_LOGIN_NAME', AUTHX_CONSTANT_CONFIGS['AUTHX_LOGIN_NAME']),
    'AUTHX_LOGOUT_NAME': getattr(settings,'AUTHX_LOGOUT_NAME', AUTHX_CONSTANT_CONFIGS['AUTHX_LOGOUT_NAME']),
    'AUTHX_REGISTER_NAME': getattr(settings,'AUTHX_REGISTER_NAME', AUTHX_CONSTANT_CONFIGS['AUTHX_REGISTER_NAME']),
    'AUTHX_SUCCESS_NAME': getattr(settings,'AUTHX_SUCCESS_NAME', AUTHX_CONSTANT_CONFIGS['AUTHX_SUCCESS_NAME']),
    'AUTHX_LOGIN_TEMPLATE': getattr(settings,'AUTHX_LOGIN_TEMPLATE', AUTHX_CONSTANT_CONFIGS['AUTHX_LOGIN_TEMPLATE']),
    'AUTHX_REGISTER_TEMPLATE': getattr(settings,'AUTHX_REGISTER_TEMPLATE', AUTHX_CONSTANT_CONFIGS['AUTHX_REGISTER_TEMPLATE']),
}